CLASS zcl_lab_39_eagm_budget DEFINITION ABSTRACT
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS:
        get_bugdet ABSTRACT RETURNING VALUE(rv_bugdet) TYPE string .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_39_EAGM_BUDGET IMPLEMENTATION.
ENDCLASS.
