CLASS zcl_lab_12_eagm_linux DEFINITION INHERITING FROM zcl_lab_11_eagm_system
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_12_EAGM_LINUX IMPLEMENTATION.
ENDCLASS.
