CLASS zcl_lab_23_eagm_company DEFINITION
  PUBLIC
  CREATE PUBLIC GLOBAL FRIENDS zcl_lab_24_eagm_partner.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA:
        capital TYPE string VALUE 'Default Capital'.
ENDCLASS.



CLASS ZCL_LAB_23_EAGM_COMPANY IMPLEMENTATION.
ENDCLASS.
