CLASS zcl_lab_21_eagm_classroom DEFINITION
  PUBLIC
  CREATE PROTECTED .
*  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_21_EAGM_CLASSROOM IMPLEMENTATION.
ENDCLASS.
