CLASS zcl_lab_40_eagm_actual_budget DEFINITION INHERITING FROM zcl_lab_39_eagm_budget
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS: get_bugdet REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_40_EAGM_ACTUAL_BUDGET IMPLEMENTATION.


  METHOD get_bugdet.

  ENDMETHOD.
ENDCLASS.
