CLASS zcx_lab_55_eagm_auth_iban DEFINITION
  PUBLIC
  FINAL
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_lab_55_eagm_auth_iban IMPLEMENTATION.
ENDCLASS.
