CLASS zcx_lab_56_eagm_no_date DEFINITION
  PUBLIC
  FINAL
  INHERITING FROM cx_static_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_lab_56_eagm_no_date IMPLEMENTATION.
ENDCLASS.
